### ISSUE TITLE
Something wrong in latest commit

### ISSUE THREAD

**Issue by herromega** [olafhartong/sysmon-modular#146]
The latest build of xml cannot be imported in sysmon/sysmon64. 
(yes I know I should modify to my needs.. but..)

I'm using latest release of sysmon. 
If im going back to a previous release it works great. So it seems to be some kind of blind character messing something up. 

It throws an errormessage like below
_"Loading configuration file with schema version 4.60
Sysmon schema version: 4.82
Error: Unknown condition: begin wi
Expected values are is, is not, contains, contains any, is any, contains all, excludes, excludes any, excludes all, begin with, end with, less than, more than, image, not begin with, not end withError: Failed to convert EventFiltering nodes: sysmonconfig.xml"_

**Comment by zward1** [comment]
Also having this issue -- I was not able to figure it out for quite a bit of time due to the way I push the config with a script.  Installing with the config fails for the same reason as above:
"Error: Unknown condition: begin wi"

I hope this gets updated/fixed.  Until then I am going back to sysmon 13.34.  For those who need it and cannot find a way to grab earlier versions, you can use the archive.org to go back to august 15th (the day before sysmon version 14 was released) and grab the sysmon.zip.

Here is a link:
http://web.archive.org/web/20220815065255/https://docs.microsoft.com/en-us/sysinternals/downloads/sysmon

**Comment by KimkimCyber** [comment]
the error is on line 1467
Change the wi to with and it solves the problem

**Comment by ibtavsan** [comment]
checked today, as @KimkimCyber said there is a typo at the 1467th line. line goes with **"begin wi"** , just correcting it to **"begin with"** fixed the issue. thanks @KimkimCyber!

**Comment by olafhartong** [comment]
Apologies guys, I've fixed it in the last commit. Thanks for reaching out!
