### ISSUE TITLE
Default config - file deletes are being archived

### ISSUE THREAD

**Issue by leepfrog-ger** [olafhartong/sysmon-modular#166]
Thanks for your work on this!

I'm just getting started to take the [default configuration](https://raw.githubusercontent.com/olafhartong/sysmon-modular/master/sysmonconfig.xml), play a bit with it and adjust it to my needs. One thing I noticed is that file deletions are archived, even though from reading the [documentation](https://github.com/olafhartong/sysmon-modular/wiki/Configuration-options#generating-the-default-configuration) I assumed this would not be the case: 

> All with the exception of FileDelete events and ClipboardEvents. these have been disabled for disk space preservation and privacy reasons.

Is this intended and I am missing or misunderstanding something?

**Comment by illumiN8i** [comment]
I'm running into this too. Large amounts of files are being preserved in the sysmon archive causing disk space issues.

**Comment by JOGit91** [comment]
Came here to say the same thing. I tracked down commit https://github.com/olafhartong/sysmon-modular/commit/c32fde3de8dcfa7b18abfc0ef7868d6526981431 where this change happened. Not sure if it was intentional or not. Like OP said, there are a couple places that says it is disabled by default. Prior to the commit, no 23 EIDs were captured by the config.

**Comment by irfaanaikagjee** [comment]
Hello, I have same issue here. Is it possible to make a sysmonconfig.xml that does not save deleted files at all?

**Comment by olafhartong** [comment]
great point, it snuck in there at some moment, I addressed that now
