### ISSUE TITLE
Events id12 with version 13.10

### ISSUE THREAD

**Issue by janlinhart-BC** [olafhartong/sysmon-modular#96]
We use your modular smoothly working on v13.02. Until recent update (operational just fine on all machines) when upgraded to version 13.10, we experienced excessive amount of logs:

and especially eventID: 12 "Registry object added or deleted: 

EventType: CreateKey" 

With various images such as ossec, spoolsv, sysmon64, 

With registry key and paths such as:

registry.key:
System\CurrentControlSet\Services\Tcpip\Parameters
registry.path:
HKLM\System\CurrentControlSet\Services\Tcpip\Parameters

or

registry.key
SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections
registry.path
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Connections

It does not seems to be sysmon issue and with some other configs it works OK, but they are much slimmer. Did you come across such an problems?

thank you for all your work and sharing

**Comment by olafhartong** [comment]
Hi, thanks for reaching out.

Yes, this is a Sysmon 13.10 issue where the parsing has some bugs.
The bug that is causing it causes all Rules that are marked as AND will be processed as OR

My advise is to stay on 13.02 till the new version. there are also other parsing bugs in 13.10 that will cause additional blind spots.

The bugs are already being fixed by the Sysinternals team, together with other bugs. I expect a new version to be available within the next 2 weeks.

**Comment by jamesdeluk** [comment]
I had this `\Tcpip\Parameters` issue even on previous versions (13.01, 13.02) so added a custom exclusion.

**Comment by willemdh** [comment]
Is this issue also on 13.22?

**Comment by olafhartong** [comment]
should be fixed in 13.22 afaik
